/**
 * 📝 Profile Fields Configuration
 *
 * Configuration for profile fields based on user roles and requirements
 */

import { ProfileField, ProfileSection, UserRole } from '../types/profile.types';

// =============================================================================
// PROFILE SECTIONS CONFIGURATION
// =============================================================================

export const PROFILE_SECTIONS: ProfileSection[] = [
  {
    id: 'personal-info',
    title: 'Personal Information',
    description: 'Basic personal and contact information',
    fields: [],
    required: true,
    order: 1,
  },
  {
    id: 'professional-background',
    title: 'Professional Background',
    description: 'Your professional experience and credentials',
    fields: [],
    required: true,
    order: 2,
    roleSpecific: ['seller', 'both'],
  },
  {
    id: 'business-context',
    title: 'Business Context',
    description: 'Information about your business and industry',
    fields: [],
    required: true,
    order: 3,
    roleSpecific: ['seller', 'both'],
  },
  {
    id: 'investment-profile',
    title: 'Investment Profile',
    description: 'Your investment preferences and capabilities',
    fields: [],
    required: true,
    order: 2,
    roleSpecific: ['buyer', 'both'],
  },
  {
    id: 'communication-preferences',
    title: 'Communication Preferences',
    description: 'How you prefer to communicate and be contacted',
    fields: [],
    required: false,
    order: 4,
  },
  {
    id: 'privacy-settings',
    title: 'Privacy Settings',
    description: 'Control who can see your information',
    fields: [],
    required: false,
    order: 5,
  },
];

// =============================================================================
// PROFILE FIELDS CONFIGURATION
// =============================================================================

export const PROFILE_FIELDS: ProfileField[] = [
  // Personal Information Fields
  {
    id: 'firstName',
    name: 'firstName',
    type: 'text',
    label: 'First Name',
    placeholder: 'Enter your first name',
    required: true,
    validation: {
      minLength: 2,
      maxLength: 50,
      required: true,
    },
    order: 1,
    privacyLevel: 'public',
  },
  {
    id: 'lastName',
    name: 'lastName',
    type: 'text',
    label: 'Last Name',
    placeholder: 'Enter your last name',
    required: true,
    validation: {
      minLength: 2,
      maxLength: 50,
      required: true,
    },
    order: 2,
    privacyLevel: 'public',
  },
  {
    id: 'email',
    name: 'email',
    type: 'email',
    label: 'Email Address',
    placeholder: 'Enter your email address',
    required: true,
    validation: {
      pattern: '^[^@]+@[^@]+\\.[^@]+$',
      required: true,
    },
    order: 3,
    privacyLevel: 'private',
  },
  {
    id: 'phone',
    name: 'phone',
    type: 'phone',
    label: 'Phone Number',
    placeholder: 'Enter your phone number',
    required: false,
    validation: {
      pattern: '^\\+?[1-9]\\d{1,14}$',
    },
    order: 4,
    privacyLevel: 'private',
  },
  {
    id: 'professionalTitle',
    name: 'professionalTitle',
    type: 'text',
    label: 'Professional Title',
    placeholder: 'e.g., CEO, Managing Director, Business Owner',
    required: false,
    validation: {
      maxLength: 100,
    },
    order: 5,
    privacyLevel: 'public',
  },
  {
    id: 'company',
    name: 'company',
    type: 'text',
    label: 'Company',
    placeholder: 'Enter your company name',
    required: false,
    validation: {
      maxLength: 100,
    },
    order: 6,
    privacyLevel: 'public',
  },
  {
    id: 'industry',
    name: 'industry',
    type: 'select',
    label: 'Industry',
    placeholder: 'Select your industry',
    required: true,
    options: [
      { value: 'technology', label: 'Technology' },
      { value: 'manufacturing', label: 'Manufacturing' },
      { value: 'retail', label: 'Retail' },
      { value: 'services', label: 'Services' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'finance', label: 'Finance' },
      { value: 'real-estate', label: 'Real Estate' },
      { value: 'construction', label: 'Construction' },
      { value: 'food-beverage', label: 'Food & Beverage' },
      { value: 'education', label: 'Education' },
      { value: 'consulting', label: 'Consulting' },
      { value: 'other', label: 'Other' },
    ],
    order: 7,
    privacyLevel: 'public',
  },
  {
    id: 'city',
    name: 'city',
    type: 'text',
    label: 'City',
    placeholder: 'Enter your city',
    required: false,
    validation: {
      maxLength: 50,
    },
    order: 8,
    privacyLevel: 'public',
  },
  {
    id: 'country',
    name: 'country',
    type: 'select',
    label: 'Country',
    placeholder: 'Select your country',
    required: true,
    options: [
      { value: 'BE', label: 'Belgium' },
      { value: 'NL', label: 'Netherlands' },
      { value: 'FR', label: 'France' },
      { value: 'DE', label: 'Germany' },
      { value: 'UK', label: 'United Kingdom' },
      { value: 'US', label: 'United States' },
      { value: 'other', label: 'Other' },
    ],
    order: 9,
    privacyLevel: 'public',
  },
  {
    id: 'bio',
    name: 'bio',
    type: 'textarea',
    label: 'Professional Bio',
    placeholder: 'Tell us about yourself and your professional background...',
    required: false,
    validation: {
      maxLength: 500,
    },
    helpText: 'A brief professional summary that will be visible to other users',
    order: 10,
    privacyLevel: 'public',
  },

  // Business Owner Specific Fields
  {
    id: 'businessName',
    name: 'businessName',
    type: 'text',
    label: 'Business Name',
    placeholder: 'Enter your business name',
    required: true,
    validation: {
      minLength: 2,
      maxLength: 100,
      required: true,
    },
    order: 1,
    roleSpecific: ['seller', 'both'],
    privacyLevel: 'public',
  },
  {
    id: 'businessType',
    name: 'businessType',
    type: 'select',
    label: 'Business Type',
    placeholder: 'Select your business type',
    required: true,
    options: [
      { value: 'sole-proprietorship', label: 'Sole Proprietorship' },
      { value: 'partnership', label: 'Partnership' },
      { value: 'llc', label: 'Limited Liability Company (LLC)' },
      { value: 'corporation', label: 'Corporation' },
      { value: 's-corp', label: 'S-Corporation' },
      { value: 'b-corp', label: 'B-Corporation' },
      { value: 'non-profit', label: 'Non-Profit' },
      { value: 'other', label: 'Other' },
    ],
    order: 2,
    roleSpecific: ['seller', 'both'],
    privacyLevel: 'public',
  },
  {
    id: 'yearsInBusiness',
    name: 'yearsInBusiness',
    type: 'number',
    label: 'Years in Business',
    placeholder: 'Enter number of years',
    required: true,
    validation: {
      min: 0,
      max: 100,
      required: true,
    },
    order: 3,
    roleSpecific: ['seller', 'both'],
    privacyLevel: 'public',
  },
  {
    id: 'yearsInIndustry',
    name: 'yearsInIndustry',
    type: 'number',
    label: 'Years in Industry',
    placeholder: 'Enter number of years',
    required: false,
    validation: {
      min: 0,
      max: 100,
    },
    order: 4,
    roleSpecific: ['seller', 'both'],
    privacyLevel: 'public',
  },
  {
    id: 'revenueRange',
    name: 'revenueRange',
    type: 'select',
    label: 'Annual Revenue Range',
    placeholder: 'Select revenue range',
    required: false,
    options: [
      { value: '0-100k', label: '€0 - €100K' },
      { value: '100k-500k', label: '€100K - €500K' },
      { value: '500k-1m', label: '€500K - €1M' },
      { value: '1m-5m', label: '€1M - €5M' },
      { value: '5m-10m', label: '€5M - €10M' },
      { value: '10m+', label: '€10M+' },
    ],
    order: 5,
    roleSpecific: ['seller', 'both'],
    privacyLevel: 'verified-only',
  },
  {
    id: 'employeeCount',
    name: 'employeeCount',
    type: 'number',
    label: 'Number of Employees',
    placeholder: 'Enter number of employees',
    required: false,
    validation: {
      min: 0,
      max: 10000,
    },
    order: 6,
    roleSpecific: ['seller', 'both'],
    privacyLevel: 'public',
  },
  {
    id: 'exitTimeline',
    name: 'exitTimeline',
    type: 'select',
    label: 'Exit Timeline',
    placeholder: 'When are you planning to exit?',
    required: false,
    options: [
      { value: 'immediate', label: 'Immediate (0-3 months)' },
      { value: '6-months', label: '6 months' },
      { value: '1-year', label: '1 year' },
      { value: '2-years', label: '2 years' },
      { value: 'flexible', label: 'Flexible' },
    ],
    order: 7,
    roleSpecific: ['seller', 'both'],
    privacyLevel: 'verified-only',
  },
  {
    id: 'reasonForSelling',
    name: 'reasonForSelling',
    type: 'textarea',
    label: 'Reason for Selling',
    placeholder: 'Why are you considering selling your business?',
    required: false,
    validation: {
      maxLength: 300,
    },
    order: 8,
    roleSpecific: ['seller', 'both'],
    privacyLevel: 'verified-only',
  },

  // Investor Specific Fields
  {
    id: 'investmentCapacityMin',
    name: 'investmentCapacityMin',
    type: 'number',
    label: 'Minimum Investment Amount',
    placeholder: 'Enter minimum amount',
    required: true,
    validation: {
      min: 0,
      required: true,
    },
    order: 1,
    roleSpecific: ['buyer', 'both'],
    privacyLevel: 'verified-only',
  },
  {
    id: 'investmentCapacityMax',
    name: 'investmentCapacityMax',
    type: 'number',
    label: 'Maximum Investment Amount',
    placeholder: 'Enter maximum amount',
    required: true,
    validation: {
      min: 0,
      required: true,
    },
    order: 2,
    roleSpecific: ['buyer', 'both'],
    privacyLevel: 'verified-only',
  },
  {
    id: 'investmentFocus',
    name: 'investmentFocus',
    type: 'multiselect',
    label: 'Investment Focus',
    placeholder: 'Select industries of interest',
    required: true,
    options: [
      { value: 'technology', label: 'Technology' },
      { value: 'manufacturing', label: 'Manufacturing' },
      { value: 'retail', label: 'Retail' },
      { value: 'services', label: 'Services' },
      { value: 'healthcare', label: 'Healthcare' },
      { value: 'finance', label: 'Finance' },
      { value: 'real-estate', label: 'Real Estate' },
      { value: 'construction', label: 'Construction' },
      { value: 'food-beverage', label: 'Food & Beverage' },
      { value: 'education', label: 'Education' },
      { value: 'consulting', label: 'Consulting' },
    ],
    order: 3,
    roleSpecific: ['buyer', 'both'],
    privacyLevel: 'public',
  },
  {
    id: 'investmentExperience',
    name: 'investmentExperience',
    type: 'number',
    label: 'Years of Investment Experience',
    placeholder: 'Enter number of years',
    required: false,
    validation: {
      min: 0,
      max: 50,
    },
    order: 4,
    roleSpecific: ['buyer', 'both'],
    privacyLevel: 'public',
  },
  {
    id: 'totalDeals',
    name: 'totalDeals',
    type: 'number',
    label: 'Total Deals Completed',
    placeholder: 'Enter number of deals',
    required: false,
    validation: {
      min: 0,
      max: 1000,
    },
    order: 5,
    roleSpecific: ['buyer', 'both'],
    privacyLevel: 'public',
  },
  {
    id: 'decisionTimeline',
    name: 'decisionTimeline',
    type: 'select',
    label: 'Decision Timeline',
    placeholder: 'How quickly do you typically make decisions?',
    required: false,
    options: [
      { value: 'immediate', label: 'Immediate (same day)' },
      { value: '1-week', label: '1 week' },
      { value: '2-weeks', label: '2 weeks' },
      { value: '1-month', label: '1 month' },
      { value: 'flexible', label: 'Flexible' },
    ],
    order: 6,
    roleSpecific: ['buyer', 'both'],
    privacyLevel: 'public',
  },

  // Communication Preferences
  {
    id: 'preferredContactMethod',
    name: 'preferredContactMethod',
    type: 'select',
    label: 'Preferred Contact Method',
    placeholder: 'How would you like to be contacted?',
    required: false,
    options: [
      { value: 'email', label: 'Email' },
      { value: 'phone', label: 'Phone' },
      { value: 'platform', label: 'Platform Messaging' },
      { value: 'any', label: 'Any Method' },
    ],
    order: 1,
    privacyLevel: 'private',
  },
  {
    id: 'responseTimeCommitment',
    name: 'responseTimeCommitment',
    type: 'select',
    label: 'Response Time Commitment',
    placeholder: 'How quickly do you typically respond?',
    required: false,
    options: [
      { value: 'immediate', label: 'Immediate (within hours)' },
      { value: '24-hours', label: 'Within 24 hours' },
      { value: '48-hours', label: 'Within 48 hours' },
      { value: '1-week', label: 'Within 1 week' },
      { value: 'flexible', label: 'Flexible' },
    ],
    order: 2,
    privacyLevel: 'public',
  },
  {
    id: 'languagePreferences',
    name: 'languagePreferences',
    type: 'multiselect',
    label: 'Language Preferences',
    placeholder: 'Select your preferred languages',
    required: false,
    options: [
      { value: 'en', label: 'English' },
      { value: 'nl', label: 'Dutch' },
      { value: 'fr', label: 'French' },
      { value: 'de', label: 'German' },
      { value: 'es', label: 'Spanish' },
      { value: 'it', label: 'Italian' },
    ],
    order: 3,
    privacyLevel: 'private',
  },
  {
    id: 'communicationStyle',
    name: 'communicationStyle',
    type: 'select',
    label: 'Communication Style',
    placeholder: 'How do you prefer to communicate?',
    required: false,
    options: [
      { value: 'formal', label: 'Formal' },
      { value: 'professional', label: 'Professional' },
      { value: 'casual', label: 'Casual' },
    ],
    order: 4,
    privacyLevel: 'private',
  },

  // Privacy Settings
  {
    id: 'profileVisibility',
    name: 'profileVisibility',
    type: 'select',
    label: 'Profile Visibility',
    placeholder: 'Who can see your profile?',
    required: false,
    options: [
      { value: 'public', label: 'Public (everyone)' },
      { value: 'verified-only', label: 'Verified users only' },
      { value: 'private', label: 'Private (invite only)' },
    ],
    order: 1,
    privacyLevel: 'private',
  },
  {
    id: 'showEmail',
    name: 'showEmail',
    type: 'select',
    label: 'Show Email Address',
    required: false,
    order: 2,
    privacyLevel: 'private',
  },
  {
    id: 'showPhone',
    name: 'showPhone',
    type: 'select',
    label: 'Show Phone Number',
    required: false,
    order: 3,
    privacyLevel: 'private',
  },
  {
    id: 'allowMessages',
    name: 'allowMessages',
    type: 'select',
    label: 'Allow Direct Messages',
    required: false,
    order: 4,
    privacyLevel: 'private',
  },
  {
    id: 'searchable',
    name: 'searchable',
    type: 'select',
    label: 'Make Profile Searchable',
    required: false,
    order: 5,
    privacyLevel: 'private',
  },
];

// =============================================================================
// FIELD GROUPING BY SECTION
// =============================================================================

export const FIELDS_BY_SECTION: Record<string, string[]> = {
  'personal-info': [
    'firstName',
    'lastName',
    'email',
    'phone',
    'professionalTitle',
    'company',
    'industry',
    'city',
    'country',
    'bio',
  ],
  'professional-background': ['businessName', 'businessType', 'yearsInBusiness', 'yearsInIndustry'],
  'business-context': ['revenueRange', 'employeeCount', 'exitTimeline', 'reasonForSelling'],
  'investment-profile': [
    'investmentCapacityMin',
    'investmentCapacityMax',
    'investmentFocus',
    'investmentExperience',
    'totalDeals',
    'decisionTimeline',
  ],
  'communication-preferences': [
    'preferredContactMethod',
    'responseTimeCommitment',
    'languagePreferences',
    'communicationStyle',
  ],
  'privacy-settings': [
    'profileVisibility',
    'showEmail',
    'showPhone',
    'allowMessages',
    'searchable',
  ],
};

// =============================================================================
// REQUIRED FIELDS BY ROLE
// =============================================================================

export const REQUIRED_FIELDS_BY_ROLE: Record<UserRole, string[]> = {
  buyer: [
    'firstName',
    'lastName',
    'email',
    'industry',
    'country',
    'investmentCapacityMin',
    'investmentCapacityMax',
    'investmentFocus',
  ],
  seller: [
    'firstName',
    'lastName',
    'email',
    'industry',
    'country',
    'businessName',
    'businessType',
    'yearsInBusiness',
  ],
  both: [
    'firstName',
    'lastName',
    'email',
    'industry',
    'country',
    'businessName',
    'businessType',
    'yearsInBusiness',
    'investmentCapacityMin',
    'investmentCapacityMax',
    'investmentFocus',
  ],
  admin: ['firstName', 'lastName', 'email', 'country'],
};

// =============================================================================
// FIELD VALIDATION RULES
// =============================================================================

export const FIELD_VALIDATION_RULES = {
  email: {
    pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    message: 'Please enter a valid email address',
  },
  phone: {
    pattern: /^\+?[1-9]\d{1,14}$/,
    message: 'Please enter a valid phone number',
  },
  url: {
    pattern: /^https?:\/\/.+/,
    message: 'Please enter a valid URL starting with http:// or https://',
  },
  minLength: (min: number) => ({
    min,
    message: `Must be at least ${min} characters long`,
  }),
  maxLength: (max: number) => ({
    max,
    message: `Must be no more than ${max} characters long`,
  }),
  min: (min: number) => ({
    min,
    message: `Must be at least ${min}`,
  }),
  max: (max: number) => ({
    max,
    message: `Must be no more than ${max}`,
  }),
};
