/**
 * 📋 Profile Templates Configuration
 *
 * Role-based profile templates and default configurations
 */

import { UserRole } from '@/shared/types';
import { Profile } from '../types/profile.types';

// =============================================================================
// PROFILE TEMPLATES BY ROLE
// =============================================================================

export const PROFILE_TEMPLATES: Record<UserRole, ProfileTemplate> = {
  buyer: {
    role: 'buyer',
    name: 'Investor Profile',
    description: 'Professional profile for business investors and buyers',
    sections: [
      'personal-info',
      'investment-profile',
      'communication-preferences',
      'privacy-settings',
    ],
    defaultData: {
      personalInfo: {
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        professionalTitle: '',
        company: '',
        industry: '',
        city: '',
        country: 'BE',
        timezone: 'Europe/Brussels',
        bio: '',
        professionalSummary: '',
      },
      investorData: {
        investmentCapacity: {
          minAmount: 0,
          maxAmount: 0,
          preferredRange: '',
          currency: 'EUR',
          availableCapital: 0,
          investmentFrequency: 'one-time',
        },
        investmentFocus: {
          industries: [],
          businessSizes: [],
          businessStages: [],
          geographicRegions: [],
          businessModels: [],
          specializations: [],
        },
        dealPreferences: {
          dealSize: '',
          dealStructure: [],
          ownershipPercentage: { min: 0, max: 100 },
          involvementLevel: 'active',
          exitStrategy: [],
          dealTimeline: '',
        },
        investmentExperience: {
          yearsActive: 0,
          totalDeals: 0,
          successfulExits: 0,
          averageDealSize: 0,
          investmentPhilosophy: '',
          riskTolerance: 'moderate',
        },
        previousDeals: [],
        professionalCredentials: [],
        teamInfo: {
          teamSize: 1,
          keyMembers: [],
          expertiseAreas: [],
          externalAdvisors: [],
          decisionMakingProcess: '',
        },
        decisionProcess: {
          decisionTimeline: '',
          decisionMakers: [],
          approvalProcess: '',
          dueDiligenceRequirements: [],
          keyCriteria: [],
        },
        dueDiligenceCapabilities: {
          financialAnalysis: false,
          legalReview: false,
          marketAnalysis: false,
          operationalReview: false,
          technicalAssessment: false,
          externalAdvisors: [],
          typicalTimeline: '',
        },
        timelineExpectations: {
          initialResponse: '',
          dueDiligencePeriod: '',
          decisionTimeline: '',
          closingTimeline: '',
          flexibility: 'moderate',
        },
        financialCapacity: {
          liquidCapital: 0,
          totalAssets: 0,
          debtCapacity: 0,
          fundingPartners: [],
          proofOfFunds: false,
          lastUpdated: '',
        },
        fundingSource: {
          source: 'personal',
          fundName: '',
          fundSize: 0,
          limitedPartners: [],
          investmentCommittee: [],
        },
        investmentStructure: {
          preferredStructure: [],
          taxConsiderations: [],
          legalStructure: [],
          reportingRequirements: [],
        },
      },
      sharedData: {
        communication: {
          preferredContactMethod: 'email',
          responseTimeCommitment: '24-hours',
          availabilitySchedule: {
            timezone: 'Europe/Brussels',
            workingHours: {
              start: '09:00',
              end: '17:00',
              days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            },
            unavailablePeriods: [],
            emergencyContact: false,
          },
          languagePreferences: ['en'],
          communicationStyle: 'professional',
          meetingPreferences: {
            preferredFormat: ['video', 'phone'],
            preferredTimes: ['morning', 'afternoon'],
            calendarIntegration: false,
            meetingDuration: '60',
            preparationRequired: true,
          },
          notificationSettings: {
            emailNotifications: true,
            pushNotifications: true,
            smsNotifications: false,
            marketingEmails: false,
            listingUpdates: true,
            messageNotifications: true,
            priceAlerts: true,
            weeklyDigest: true,
          },
        },
        professionalNetwork: {
          linkedinUrl: '',
          professionalAssociations: [],
          industryConnections: 0,
          referralNetwork: [],
          mentorship: {
            offering: false,
            seeking: false,
            areas: [],
          },
        },
        platformActivity: {
          memberSince: '',
          lastActiveAt: '',
          profileViews: 0,
          messagesSent: 0,
          messagesReceived: 0,
          listingsViewed: 0,
          inquiriesSent: 0,
          inquiriesReceived: 0,
          transactionsCompleted: 0,
          averageResponseTime: 0,
          userRating: 0,
          reviewCount: 0,
        },
        privacy: {
          profileVisibility: 'public',
          showEmail: false,
          showPhone: false,
          showLocation: true,
          allowMessages: true,
          allowInquiries: true,
          dataSharing: false,
          anonymousProfile: false,
          searchable: true,
        },
      },
    },
    requiredFields: [
      'firstName',
      'lastName',
      'email',
      'industry',
      'country',
      'investmentCapacityMin',
      'investmentCapacityMax',
      'investmentFocus',
    ],
    optionalFields: [
      'phone',
      'professionalTitle',
      'company',
      'city',
      'bio',
      'investmentExperience',
      'totalDeals',
      'decisionTimeline',
      'preferredContactMethod',
      'responseTimeCommitment',
      'languagePreferences',
      'communicationStyle',
    ],
  },

  seller: {
    role: 'seller',
    name: 'Business Owner Profile',
    description: 'Professional profile for business owners and sellers',
    sections: [
      'personal-info',
      'professional-background',
      'business-context',
      'communication-preferences',
      'privacy-settings',
    ],
    defaultData: {
      personalInfo: {
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        professionalTitle: '',
        company: '',
        industry: '',
        city: '',
        country: 'BE',
        timezone: 'Europe/Brussels',
        bio: '',
        professionalSummary: '',
      },
      businessOwnerData: {
        businessName: '',
        businessType: '',
        businessModel: '',
        industry: '',
        yearsInBusiness: 0,
        yearsInIndustry: 0,
        currentRole: '',
        responsibilities: [],
        previousVentures: [],
        professionalCertifications: [],
        industryExpertise: [],
        keyAchievements: [],
        industryAwards: [],
        professionalNetwork: '',
        exitTimeline: {
          timeframe: 'flexible',
          urgency: 'low',
          flexibility: 'flexible',
          notes: '',
        },
        reasonForSelling: '',
        preferredExitType: 'both',
        revenueRange: '',
        employeeCount: 0,
        businessAge: 0,
        growthRate: 0,
      },
      sharedData: {
        communication: {
          preferredContactMethod: 'email',
          responseTimeCommitment: '24-hours',
          availabilitySchedule: {
            timezone: 'Europe/Brussels',
            workingHours: {
              start: '09:00',
              end: '17:00',
              days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            },
            unavailablePeriods: [],
            emergencyContact: false,
          },
          languagePreferences: ['en'],
          communicationStyle: 'professional',
          meetingPreferences: {
            preferredFormat: ['video', 'phone'],
            preferredTimes: ['morning', 'afternoon'],
            calendarIntegration: false,
            meetingDuration: '60',
            preparationRequired: true,
          },
          notificationSettings: {
            emailNotifications: true,
            pushNotifications: true,
            smsNotifications: false,
            marketingEmails: false,
            listingUpdates: true,
            messageNotifications: true,
            priceAlerts: true,
            weeklyDigest: true,
          },
        },
        professionalNetwork: {
          linkedinUrl: '',
          professionalAssociations: [],
          industryConnections: 0,
          referralNetwork: [],
          mentorship: {
            offering: false,
            seeking: false,
            areas: [],
          },
        },
        platformActivity: {
          memberSince: '',
          lastActiveAt: '',
          profileViews: 0,
          messagesSent: 0,
          messagesReceived: 0,
          listingsViewed: 0,
          inquiriesSent: 0,
          inquiriesReceived: 0,
          transactionsCompleted: 0,
          averageResponseTime: 0,
          userRating: 0,
          reviewCount: 0,
        },
        privacy: {
          profileVisibility: 'public',
          showEmail: false,
          showPhone: false,
          showLocation: true,
          allowMessages: true,
          allowInquiries: true,
          dataSharing: false,
          anonymousProfile: false,
          searchable: true,
        },
      },
    },
    requiredFields: [
      'firstName',
      'lastName',
      'email',
      'industry',
      'country',
      'businessName',
      'businessType',
      'yearsInBusiness',
    ],
    optionalFields: [
      'phone',
      'professionalTitle',
      'company',
      'city',
      'bio',
      'businessModel',
      'yearsInIndustry',
      'revenueRange',
      'employeeCount',
      'exitTimeline',
      'reasonForSelling',
      'preferredContactMethod',
      'responseTimeCommitment',
      'languagePreferences',
      'communicationStyle',
    ],
  },

  both: {
    role: 'both',
    name: 'Dual Role Profile',
    description: 'Comprehensive profile for users who are both buyers and sellers',
    sections: [
      'personal-info',
      'professional-background',
      'business-context',
      'investment-profile',
      'communication-preferences',
      'privacy-settings',
    ],
    defaultData: {
      personalInfo: {
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        professionalTitle: '',
        company: '',
        industry: '',
        city: '',
        country: 'BE',
        timezone: 'Europe/Brussels',
        bio: '',
        professionalSummary: '',
      },
      businessOwnerData: {
        businessName: '',
        businessType: '',
        businessModel: '',
        industry: '',
        yearsInBusiness: 0,
        yearsInIndustry: 0,
        currentRole: '',
        responsibilities: [],
        previousVentures: [],
        professionalCertifications: [],
        industryExpertise: [],
        keyAchievements: [],
        industryAwards: [],
        professionalNetwork: '',
        exitTimeline: {
          timeframe: 'flexible',
          urgency: 'low',
          flexibility: 'flexible',
          notes: '',
        },
        reasonForSelling: '',
        preferredExitType: 'both',
        revenueRange: '',
        employeeCount: 0,
        businessAge: 0,
        growthRate: 0,
      },
      investorData: {
        investmentCapacity: {
          minAmount: 0,
          maxAmount: 0,
          preferredRange: '',
          currency: 'EUR',
          availableCapital: 0,
          investmentFrequency: 'one-time',
        },
        investmentFocus: {
          industries: [],
          businessSizes: [],
          businessStages: [],
          geographicRegions: [],
          businessModels: [],
          specializations: [],
        },
        dealPreferences: {
          dealSize: '',
          dealStructure: [],
          ownershipPercentage: { min: 0, max: 100 },
          involvementLevel: 'active',
          exitStrategy: [],
          dealTimeline: '',
        },
        investmentExperience: {
          yearsActive: 0,
          totalDeals: 0,
          successfulExits: 0,
          averageDealSize: 0,
          investmentPhilosophy: '',
          riskTolerance: 'moderate',
        },
        previousDeals: [],
        professionalCredentials: [],
        teamInfo: {
          teamSize: 1,
          keyMembers: [],
          expertiseAreas: [],
          externalAdvisors: [],
          decisionMakingProcess: '',
        },
        decisionProcess: {
          decisionTimeline: '',
          decisionMakers: [],
          approvalProcess: '',
          dueDiligenceRequirements: [],
          keyCriteria: [],
        },
        dueDiligenceCapabilities: {
          financialAnalysis: false,
          legalReview: false,
          marketAnalysis: false,
          operationalReview: false,
          technicalAssessment: false,
          externalAdvisors: [],
          typicalTimeline: '',
        },
        timelineExpectations: {
          initialResponse: '',
          dueDiligencePeriod: '',
          decisionTimeline: '',
          closingTimeline: '',
          flexibility: 'moderate',
        },
        financialCapacity: {
          liquidCapital: 0,
          totalAssets: 0,
          debtCapacity: 0,
          fundingPartners: [],
          proofOfFunds: false,
          lastUpdated: '',
        },
        fundingSource: {
          source: 'personal',
          fundName: '',
          fundSize: 0,
          limitedPartners: [],
          investmentCommittee: [],
        },
        investmentStructure: {
          preferredStructure: [],
          taxConsiderations: [],
          legalStructure: [],
          reportingRequirements: [],
        },
      },
      sharedData: {
        communication: {
          preferredContactMethod: 'email',
          responseTimeCommitment: '24-hours',
          availabilitySchedule: {
            timezone: 'Europe/Brussels',
            workingHours: {
              start: '09:00',
              end: '17:00',
              days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            },
            unavailablePeriods: [],
            emergencyContact: false,
          },
          languagePreferences: ['en'],
          communicationStyle: 'professional',
          meetingPreferences: {
            preferredFormat: ['video', 'phone'],
            preferredTimes: ['morning', 'afternoon'],
            calendarIntegration: false,
            meetingDuration: '60',
            preparationRequired: true,
          },
          notificationSettings: {
            emailNotifications: true,
            pushNotifications: true,
            smsNotifications: false,
            marketingEmails: false,
            listingUpdates: true,
            messageNotifications: true,
            priceAlerts: true,
            weeklyDigest: true,
          },
        },
        professionalNetwork: {
          linkedinUrl: '',
          professionalAssociations: [],
          industryConnections: 0,
          referralNetwork: [],
          mentorship: {
            offering: false,
            seeking: false,
            areas: [],
          },
        },
        platformActivity: {
          memberSince: '',
          lastActiveAt: '',
          profileViews: 0,
          messagesSent: 0,
          messagesReceived: 0,
          listingsViewed: 0,
          inquiriesSent: 0,
          inquiriesReceived: 0,
          transactionsCompleted: 0,
          averageResponseTime: 0,
          userRating: 0,
          reviewCount: 0,
        },
        privacy: {
          profileVisibility: 'public',
          showEmail: false,
          showPhone: false,
          showLocation: true,
          allowMessages: true,
          allowInquiries: true,
          dataSharing: false,
          anonymousProfile: false,
          searchable: true,
        },
      },
    },
    requiredFields: [
      'firstName',
      'lastName',
      'email',
      'industry',
      'country',
      'businessName',
      'businessType',
      'yearsInBusiness',
      'investmentCapacityMin',
      'investmentCapacityMax',
      'investmentFocus',
    ],
    optionalFields: [
      'phone',
      'professionalTitle',
      'company',
      'city',
      'bio',
      'businessModel',
      'yearsInIndustry',
      'revenueRange',
      'employeeCount',
      'exitTimeline',
      'reasonForSelling',
      'investmentExperience',
      'totalDeals',
      'decisionTimeline',
      'preferredContactMethod',
      'responseTimeCommitment',
      'languagePreferences',
      'communicationStyle',
    ],
  },

  admin: {
    role: 'admin',
    name: 'Administrator Profile',
    description: 'Administrative profile for platform administrators',
    sections: ['personal-info', 'communication-preferences', 'privacy-settings'],
    defaultData: {
      personalInfo: {
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        professionalTitle: '',
        company: '',
        industry: '',
        city: '',
        country: 'BE',
        timezone: 'Europe/Brussels',
        bio: '',
        professionalSummary: '',
      },
      sharedData: {
        communication: {
          preferredContactMethod: 'email',
          responseTimeCommitment: 'immediate',
          availabilitySchedule: {
            timezone: 'Europe/Brussels',
            workingHours: {
              start: '09:00',
              end: '17:00',
              days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            },
            unavailablePeriods: [],
            emergencyContact: true,
          },
          languagePreferences: ['en'],
          communicationStyle: 'professional',
          meetingPreferences: {
            preferredFormat: ['video', 'phone'],
            preferredTimes: ['morning', 'afternoon'],
            calendarIntegration: true,
            meetingDuration: '30',
            preparationRequired: false,
          },
          notificationSettings: {
            emailNotifications: true,
            pushNotifications: true,
            smsNotifications: true,
            marketingEmails: false,
            listingUpdates: true,
            messageNotifications: true,
            priceAlerts: true,
            weeklyDigest: true,
          },
        },
        professionalNetwork: {
          linkedinUrl: '',
          professionalAssociations: [],
          industryConnections: 0,
          referralNetwork: [],
          mentorship: {
            offering: true,
            seeking: false,
            areas: ['platform-management', 'user-support'],
          },
        },
        platformActivity: {
          memberSince: '',
          lastActiveAt: '',
          profileViews: 0,
          messagesSent: 0,
          messagesReceived: 0,
          listingsViewed: 0,
          inquiriesSent: 0,
          inquiriesReceived: 0,
          transactionsCompleted: 0,
          averageResponseTime: 0,
          userRating: 0,
          reviewCount: 0,
        },
        privacy: {
          profileVisibility: 'private',
          showEmail: false,
          showPhone: false,
          showLocation: false,
          allowMessages: true,
          allowInquiries: false,
          dataSharing: false,
          anonymousProfile: true,
          searchable: false,
        },
      },
    },
    requiredFields: ['firstName', 'lastName', 'email', 'country'],
    optionalFields: ['phone', 'professionalTitle', 'company', 'city', 'bio'],
  },
};

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

interface ProfileTemplate {
  role: UserRole;
  name: string;
  description: string;
  sections: string[];
  defaultData: Partial<Profile>;
  requiredFields: string[];
  optionalFields: string[];
}