/**
 * 📋 Profile Templates Configuration
 *
 * Role-based profile templates and default configurations
 */

import { UserRole } from '@/shared/types';
import { Profile } from '../types/profile.types';

// =============================================================================
// PROFILE TEMPLATES BY ROLE
// =============================================================================

export const PROFILE_TEMPLATES: Record<UserRole, ProfileTemplate> = {
  buyer: {
    role: 'buyer',
    name: 'Investor Profile',
    description: 'Professional profile for business investors and buyers',
    sections: [
      'personal-info',
      'investment-profile',
      'communication-preferences',
      'privacy-settings',
    ],
    defaultData: {
      personalInfo: {
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        professionalTitle: '',
        company: '',
        industry: '',
        city: '',
        country: 'BE',
        timezone: 'Europe/Brussels',
        bio: '',
        professionalSummary: '',
      },
      investorData: {
        investmentCapacity: {
          minAmount: 0,
          maxAmount: 0,
          preferredRange: '',
          currency: 'EUR',
          availableCapital: 0,
          investmentFrequency: 'one-time',
        },
        investmentFocus: {
          industries: [],
          businessSizes: [],
          businessStages: [],
          geographicRegions: [],
          businessModels: [],
          specializations: [],
        },
        dealPreferences: {
          dealSize: '',
          dealStructure: [],
          ownershipPercentage: { min: 0, max: 100 },
          involvementLevel: 'active',
          exitStrategy: [],
          dealTimeline: '',
        },
        investmentExperience: {
          yearsActive: 0,
          totalDeals: 0,
          successfulExits: 0,
          averageDealSize: 0,
          investmentPhilosophy: '',
          riskTolerance: 'moderate',
        },
        previousDeals: [],
        professionalCredentials: [],
        teamInfo: {
          teamSize: 1,
          keyMembers: [],
          expertiseAreas: [],
          externalAdvisors: [],
          decisionMakingProcess: '',
        },
        decisionProcess: {
          decisionTimeline: '',
          decisionMakers: [],
          approvalProcess: '',
          dueDiligenceRequirements: [],
          keyCriteria: [],
        },
        dueDiligenceCapabilities: {
          financialAnalysis: false,
          legalReview: false,
          marketAnalysis: false,
          operationalReview: false,
          technicalAssessment: false,
          externalAdvisors: [],
          typicalTimeline: '',
        },
        timelineExpectations: {
          initialResponse: '',
          dueDiligencePeriod: '',
          decisionTimeline: '',
          closingTimeline: '',
          flexibility: 'moderate',
        },
        financialCapacity: {
          liquidCapital: 0,
          totalAssets: 0,
          debtCapacity: 0,
          fundingPartners: [],
          proofOfFunds: false,
          lastUpdated: '',
        },
        fundingSource: {
          source: 'personal',
          fundName: '',
          fundSize: 0,
          limitedPartners: [],
          investmentCommittee: [],
        },
        investmentStructure: {
          preferredStructure: [],
          taxConsiderations: [],
          legalStructure: [],
          reportingRequirements: [],
        },
      },
      sharedData: {
        communication: {
          preferredContactMethod: 'email',
          responseTimeCommitment: '24-hours',
          availabilitySchedule: {
            timezone: 'Europe/Brussels',
            workingHours: {
              start: '09:00',
              end: '17:00',
              days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            },
            unavailablePeriods: [],
            emergencyContact: false,
          },
          languagePreferences: ['en'],
          communicationStyle: 'professional',
          meetingPreferences: {
            preferredFormat: ['video', 'phone'],
            preferredTimes: ['morning', 'afternoon'],
            calendarIntegration: false,
            meetingDuration: '60',
            preparationRequired: true,
          },
          notificationSettings: {
            emailNotifications: true,
            pushNotifications: true,
            smsNotifications: false,
            marketingEmails: false,
            listingUpdates: true,
            messageNotifications: true,
            priceAlerts: true,
            weeklyDigest: true,
          },
        },
        professionalNetwork: {
          linkedinUrl: '',
          professionalAssociations: [],
          industryConnections: 0,
          referralNetwork: [],
          mentorship: {
            offering: false,
            seeking: false,
            areas: [],
          },
        },
        platformActivity: {
          memberSince: '',
          lastActiveAt: '',
          profileViews: 0,
          messagesSent: 0,
          messagesReceived: 0,
          listingsViewed: 0,
          inquiriesSent: 0,
          inquiriesReceived: 0,
          transactionsCompleted: 0,
          averageResponseTime: 0,
          userRating: 0,
          reviewCount: 0,
        },
        privacy: {
          profileVisibility: 'public',
          showEmail: false,
          showPhone: false,
          showLocation: true,
          allowMessages: true,
          allowInquiries: true,
          dataSharing: false,
          anonymousProfile: false,
          searchable: true,
        },
      },
    },
    requiredFields: [
      'firstName',
      'lastName',
      'email',
      'industry',
      'country',
      'investmentCapacityMin',
      'investmentCapacityMax',
      'investmentFocus',
    ],
    optionalFields: [
      'phone',
      'professionalTitle',
      'company',
      'city',
      'bio',
      'investmentExperience',
      'totalDeals',
      'decisionTimeline',
      'preferredContactMethod',
      'responseTimeCommitment',
      'languagePreferences',
      'communicationStyle',
    ],
  },

  seller: {
    role: 'seller',
    name: 'Business Owner Profile',
    description: 'Professional profile for business owners and sellers',
    sections: [
      'personal-info',
      'professional-background',
      'business-context',
      'communication-preferences',
      'privacy-settings',
    ],
    defaultData: {
      personalInfo: {
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        professionalTitle: '',
        company: '',
        industry: '',
        city: '',
        country: 'BE',
        timezone: 'Europe/Brussels',
        bio: '',
        professionalSummary: '',
      },
      businessOwnerData: {
        businessName: '',
        businessType: '',
        businessModel: '',
        industry: '',
        yearsInBusiness: 0,
        yearsInIndustry: 0,
        currentRole: '',
        responsibilities: [],
        previousVentures: [],
        professionalCertifications: [],
        industryExpertise: [],
        keyAchievements: [],
        industryAwards: [],
        professionalNetwork: '',
        exitTimeline: {
          timeframe: 'flexible',
          urgency: 'low',
          flexibility: 'flexible',
          notes: '',
        },
        reasonForSelling: '',
        preferredExitType: 'both',
        revenueRange: '',
        employeeCount: 0,
        businessAge: 0,
        growthRate: 0,
      },
      sharedData: {
        communication: {
          preferredContactMethod: 'email',
          responseTimeCommitment: '24-hours',
          availabilitySchedule: {
            timezone: 'Europe/Brussels',
            workingHours: {
              start: '09:00',
              end: '17:00',
              days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            },
            unavailablePeriods: [],
            emergencyContact: false,
          },
          languagePreferences: ['en'],
          communicationStyle: 'professional',
          meetingPreferences: {
            preferredFormat: ['video', 'phone'],
            preferredTimes: ['morning', 'afternoon'],
            calendarIntegration: false,
            meetingDuration: '60',
            preparationRequired: true,
          },
          notificationSettings: {
            emailNotifications: true,
            pushNotifications: true,
            smsNotifications: false,
            marketingEmails: false,
            listingUpdates: true,
            messageNotifications: true,
            priceAlerts: true,
            weeklyDigest: true,
          },
        },
        professionalNetwork: {
          linkedinUrl: '',
          professionalAssociations: [],
          industryConnections: 0,
          referralNetwork: [],
          mentorship: {
            offering: false,
            seeking: false,
            areas: [],
          },
        },
        platformActivity: {
          memberSince: '',
          lastActiveAt: '',
          profileViews: 0,
          messagesSent: 0,
          messagesReceived: 0,
          listingsViewed: 0,
          inquiriesSent: 0,
          inquiriesReceived: 0,
          transactionsCompleted: 0,
          averageResponseTime: 0,
          userRating: 0,
          reviewCount: 0,
        },
        privacy: {
          profileVisibility: 'public',
          showEmail: false,
          showPhone: false,
          showLocation: true,
          allowMessages: true,
          allowInquiries: true,
          dataSharing: false,
          anonymousProfile: false,
          searchable: true,
        },
      },
    },
    requiredFields: [
      'firstName',
      'lastName',
      'email',
      'industry',
      'country',
      'businessName',
      'businessType',
      'yearsInBusiness',
    ],
    optionalFields: [
      'phone',
      'professionalTitle',
      'company',
      'city',
      'bio',
      'businessModel',
      'yearsInIndustry',
      'revenueRange',
      'employeeCount',
      'exitTimeline',
      'reasonForSelling',
      'preferredContactMethod',
      'responseTimeCommitment',
      'languagePreferences',
      'communicationStyle',
    ],
  },

  both: {
    role: 'both',
    name: 'Dual Role Profile',
    description: 'Comprehensive profile for users who are both buyers and sellers',
    sections: [
      'personal-info',
      'professional-background',
      'business-context',
      'investment-profile',
      'communication-preferences',
      'privacy-settings',
    ],
    defaultData: {
      personalInfo: {
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        professionalTitle: '',
        company: '',
        industry: '',
        city: '',
        country: 'BE',
        timezone: 'Europe/Brussels',
        bio: '',
        professionalSummary: '',
      },
      businessOwnerData: {
        businessName: '',
        businessType: '',
        businessModel: '',
        industry: '',
        yearsInBusiness: 0,
        yearsInIndustry: 0,
        currentRole: '',
        responsibilities: [],
        previousVentures: [],
        professionalCertifications: [],
        industryExpertise: [],
        keyAchievements: [],
        industryAwards: [],
        professionalNetwork: '',
        exitTimeline: {
          timeframe: 'flexible',
          urgency: 'low',
          flexibility: 'flexible',
          notes: '',
        },
        reasonForSelling: '',
        preferredExitType: 'both',
        revenueRange: '',
        employeeCount: 0,
        businessAge: 0,
        growthRate: 0,
      },
      investorData: {
        investmentCapacity: {
          minAmount: 0,
          maxAmount: 0,
          preferredRange: '',
          currency: 'EUR',
          availableCapital: 0,
          investmentFrequency: 'one-time',
        },
        investmentFocus: {
          industries: [],
          businessSizes: [],
          businessStages: [],
          geographicRegions: [],
          businessModels: [],
          specializations: [],
        },
        dealPreferences: {
          dealSize: '',
          dealStructure: [],
          ownershipPercentage: { min: 0, max: 100 },
          involvementLevel: 'active',
          exitStrategy: [],
          dealTimeline: '',
        },
        investmentExperience: {
          yearsActive: 0,
          totalDeals: 0,
          successfulExits: 0,
          averageDealSize: 0,
          investmentPhilosophy: '',
          riskTolerance: 'moderate',
        },
        previousDeals: [],
        professionalCredentials: [],
        teamInfo: {
          teamSize: 1,
          keyMembers: [],
          expertiseAreas: [],
          externalAdvisors: [],
          decisionMakingProcess: '',
        },
        decisionProcess: {
          decisionTimeline: '',
          decisionMakers: [],
          approvalProcess: '',
          dueDiligenceRequirements: [],
          keyCriteria: [],
        },
        dueDiligenceCapabilities: {
          financialAnalysis: false,
          legalReview: false,
          marketAnalysis: false,
          operationalReview: false,
          technicalAssessment: false,
          externalAdvisors: [],
          typicalTimeline: '',
        },
        timelineExpectations: {
          initialResponse: '',
          dueDiligencePeriod: '',
          decisionTimeline: '',
          closingTimeline: '',
          flexibility: 'moderate',
        },
        financialCapacity: {
          liquidCapital: 0,
          totalAssets: 0,
          debtCapacity: 0,
          fundingPartners: [],
          proofOfFunds: false,
          lastUpdated: '',
        },
        fundingSource: {
          source: 'personal',
          fundName: '',
          fundSize: 0,
          limitedPartners: [],
          investmentCommittee: [],
        },
        investmentStructure: {
          preferredStructure: [],
          taxConsiderations: [],
          legalStructure: [],
          reportingRequirements: [],
        },
      },
      sharedData: {
        communication: {
          preferredContactMethod: 'email',
          responseTimeCommitment: '24-hours',
          availabilitySchedule: {
            timezone: 'Europe/Brussels',
            workingHours: {
              start: '09:00',
              end: '17:00',
              days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            },
            unavailablePeriods: [],
            emergencyContact: false,
          },
          languagePreferences: ['en'],
          communicationStyle: 'professional',
          meetingPreferences: {
            preferredFormat: ['video', 'phone'],
            preferredTimes: ['morning', 'afternoon'],
            calendarIntegration: false,
            meetingDuration: '60',
            preparationRequired: true,
          },
          notificationSettings: {
            emailNotifications: true,
            pushNotifications: true,
            smsNotifications: false,
            marketingEmails: false,
            listingUpdates: true,
            messageNotifications: true,
            priceAlerts: true,
            weeklyDigest: true,
          },
        },
        professionalNetwork: {
          linkedinUrl: '',
          professionalAssociations: [],
          industryConnections: 0,
          referralNetwork: [],
          mentorship: {
            offering: false,
            seeking: false,
            areas: [],
          },
        },
        platformActivity: {
          memberSince: '',
          lastActiveAt: '',
          profileViews: 0,
          messagesSent: 0,
          messagesReceived: 0,
          listingsViewed: 0,
          inquiriesSent: 0,
          inquiriesReceived: 0,
          transactionsCompleted: 0,
          averageResponseTime: 0,
          userRating: 0,
          reviewCount: 0,
        },
        privacy: {
          profileVisibility: 'public',
          showEmail: false,
          showPhone: false,
          showLocation: true,
          allowMessages: true,
          allowInquiries: true,
          dataSharing: false,
          anonymousProfile: false,
          searchable: true,
        },
      },
    },
    requiredFields: [
      'firstName',
      'lastName',
      'email',
      'industry',
      'country',
      'businessName',
      'businessType',
      'yearsInBusiness',
      'investmentCapacityMin',
      'investmentCapacityMax',
      'investmentFocus',
    ],
    optionalFields: [
      'phone',
      'professionalTitle',
      'company',
      'city',
      'bio',
      'businessModel',
      'yearsInIndustry',
      'revenueRange',
      'employeeCount',
      'exitTimeline',
      'reasonForSelling',
      'investmentExperience',
      'totalDeals',
      'decisionTimeline',
      'preferredContactMethod',
      'responseTimeCommitment',
      'languagePreferences',
      'communicationStyle',
    ],
  },

  admin: {
    role: 'admin',
    name: 'Administrator Profile',
    description: 'Administrative profile for platform administrators',
    sections: ['personal-info', 'communication-preferences', 'privacy-settings'],
    defaultData: {
      personalInfo: {
        firstName: '',
        lastName: '',
        email: '',
        phone: '',
        professionalTitle: '',
        company: '',
        industry: '',
        city: '',
        country: 'BE',
        timezone: 'Europe/Brussels',
        bio: '',
        professionalSummary: '',
      },
      sharedData: {
        communication: {
          preferredContactMethod: 'email',
          responseTimeCommitment: 'immediate',
          availabilitySchedule: {
            timezone: 'Europe/Brussels',
            workingHours: {
              start: '09:00',
              end: '17:00',
              days: ['monday', 'tuesday', 'wednesday', 'thursday', 'friday'],
            },
            unavailablePeriods: [],
            emergencyContact: true,
          },
          languagePreferences: ['en'],
          communicationStyle: 'professional',
          meetingPreferences: {
            preferredFormat: ['video', 'phone'],
            preferredTimes: ['morning', 'afternoon'],
            calendarIntegration: true,
            meetingDuration: '30',
            preparationRequired: false,
          },
          notificationSettings: {
            emailNotifications: true,
            pushNotifications: true,
            smsNotifications: true,
            marketingEmails: false,
            listingUpdates: true,
            messageNotifications: true,
            priceAlerts: true,
            weeklyDigest: true,
          },
        },
        professionalNetwork: {
          linkedinUrl: '',
          professionalAssociations: [],
          industryConnections: 0,
          referralNetwork: [],
          mentorship: {
            offering: true,
            seeking: false,
            areas: ['platform-management', 'user-support'],
          },
        },
        platformActivity: {
          memberSince: '',
          lastActiveAt: '',
          profileViews: 0,
          messagesSent: 0,
          messagesReceived: 0,
          listingsViewed: 0,
          inquiriesSent: 0,
          inquiriesReceived: 0,
          transactionsCompleted: 0,
          averageResponseTime: 0,
          userRating: 0,
          reviewCount: 0,
        },
        privacy: {
          profileVisibility: 'private',
          showEmail: false,
          showPhone: false,
          showLocation: false,
          allowMessages: true,
          allowInquiries: false,
          dataSharing: false,
          anonymousProfile: true,
          searchable: false,
        },
      },
    },
    requiredFields: ['firstName', 'lastName', 'email', 'country'],
    optionalFields: ['phone', 'professionalTitle', 'company', 'city', 'bio'],
  },
};

// =============================================================================
// PROFILE COMPLETION GUIDANCE
// =============================================================================

export const PROFILE_COMPLETION_GUIDANCE: Record<UserRole, ProfileCompletionGuidance> = {
  buyer: {
    title: 'Complete Your Investor Profile',
    description:
      'Build trust and credibility with business owners by completing your investor profile',
    benefits: [
      'Access to verified business listings',
      'Priority in seller communications',
      'Enhanced credibility in negotiations',
      'Professional investor badge',
    ],
    steps: [
      {
        title: 'Basic Information',
        description: 'Add your name, contact details, and professional background',
        fields: ['firstName', 'lastName', 'email', 'professionalTitle', 'company'],
        priority: 'high',
      },
      {
        title: 'Investment Profile',
        description: 'Define your investment capacity, focus areas, and preferences',
        fields: ['investmentCapacityMin', 'investmentCapacityMax', 'investmentFocus'],
        priority: 'high',
      },
      {
        title: 'Professional Experience',
        description: 'Share your investment experience and track record',
        fields: ['investmentExperience', 'totalDeals'],
        priority: 'medium',
      },
      {
        title: 'Communication Preferences',
        description: 'Set how you prefer to be contacted and respond to inquiries',
        fields: ['preferredContactMethod', 'responseTimeCommitment'],
        priority: 'medium',
      },
    ],
    tips: [
      'Be specific about your investment capacity and focus areas',
      'Include relevant professional experience and achievements',
      'Set clear communication preferences to manage expectations',
      'Upload a professional photo to build trust',
    ],
  },

  seller: {
    title: 'Complete Your Business Owner Profile',
    description: 'Showcase your business and attract serious buyers with a complete profile',
    benefits: [
      'Increased visibility in buyer searches',
      'Enhanced credibility with potential buyers',
      'Priority in buyer communications',
      'Professional business owner badge',
    ],
    steps: [
      {
        title: 'Basic Information',
        description: 'Add your name, contact details, and professional background',
        fields: ['firstName', 'lastName', 'email', 'professionalTitle', 'company'],
        priority: 'high',
      },
      {
        title: 'Business Information',
        description: 'Provide details about your business and industry',
        fields: ['businessName', 'businessType', 'industry', 'yearsInBusiness'],
        priority: 'high',
      },
      {
        title: 'Business Context',
        description: 'Share business metrics and exit strategy',
        fields: ['revenueRange', 'employeeCount', 'exitTimeline'],
        priority: 'medium',
      },
      {
        title: 'Professional Background',
        description: 'Highlight your experience and achievements',
        fields: ['yearsInIndustry', 'industryExpertise'],
        priority: 'medium',
      },
    ],
    tips: [
      'Be transparent about your business metrics and performance',
      'Clearly communicate your exit timeline and reasons for selling',
      'Highlight your industry expertise and business achievements',
      'Upload a professional photo and company logo',
    ],
  },

  both: {
    title: 'Complete Your Dual Role Profile',
    description: 'Maximize your opportunities by completing both buyer and seller profiles',
    benefits: [
      'Access to all platform features',
      'Maximum visibility in searches',
      'Enhanced credibility in both roles',
      'Professional dual role badge',
    ],
    steps: [
      {
        title: 'Basic Information',
        description: 'Add your name, contact details, and professional background',
        fields: ['firstName', 'lastName', 'email', 'professionalTitle', 'company'],
        priority: 'high',
      },
      {
        title: 'Business Information',
        description: 'Provide details about your business and industry',
        fields: ['businessName', 'businessType', 'industry', 'yearsInBusiness'],
        priority: 'high',
      },
      {
        title: 'Investment Profile',
        description: 'Define your investment capacity and focus areas',
        fields: ['investmentCapacityMin', 'investmentCapacityMax', 'investmentFocus'],
        priority: 'high',
      },
      {
        title: 'Professional Experience',
        description: 'Share your experience in both business ownership and investing',
        fields: ['investmentExperience', 'totalDeals', 'yearsInIndustry'],
        priority: 'medium',
      },
    ],
    tips: [
      'Complete both business and investment sections thoroughly',
      'Be clear about your dual role and how it benefits others',
      'Set different communication preferences for each role if needed',
      'Highlight your unique perspective as both buyer and seller',
    ],
  },

  admin: {
    title: 'Complete Your Administrator Profile',
    description: 'Set up your administrative profile for platform management',
    benefits: [
      'Access to administrative tools',
      'User support capabilities',
      'Platform management features',
      'Administrator badge',
    ],
    steps: [
      {
        title: 'Basic Information',
        description: 'Add your name and contact details',
        fields: ['firstName', 'lastName', 'email'],
        priority: 'high',
      },
      {
        title: 'Professional Information',
        description: 'Add your role and company information',
        fields: ['professionalTitle', 'company'],
        priority: 'medium',
      },
    ],
    tips: [
      'Keep your profile professional and focused on support',
      'Set appropriate communication preferences for user support',
      'Maintain privacy settings appropriate for administrators',
    ],
  },
};

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

interface ProfileTemplate {
  role: UserRole;
  name: string;
  description: string;
  sections: string[];
  defaultData: Partial<Profile>;
  requiredFields: string[];
  optionalFields: string[];
}

interface ProfileCompletionGuidance {
  title: string;
  description: string;
  benefits: string[];
  steps: ProfileCompletionStep[];
  tips: string[];
}

interface ProfileCompletionStep {
  title: string;
  description: string;
  fields: string[];
  priority: 'high' | 'medium' | 'low';
}
