#!/bin/bash

# 🚀 Environment Variable Migration Script
# Copies environment variables from legacy app deployment to new frontend

echo "🔄 Migrating Environment Variables from Legacy to New Frontend"
echo "============================================================="

echo ""
echo "📋 CRITICAL: You need to copy these environment variables from your WORKING legacy deployment:"
echo "=============================================================================="
echo ""
echo "🔍 Step 1: Get Environment Variables from Legacy Deployment"
echo "-----------------------------------------------------------"
echo ""
echo "For Vercel (Legacy App):"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Find your WORKING legacy project (betweendeals-frontend-legacy)"
echo "3. Click Settings > Environment Variables"
echo "4. Copy the values for:"
echo "   - VITE_SUPABASE_URL"
echo "   - VITE_SUPABASE_ANON_KEY"
echo ""
echo "For Railway (Legacy App):"
echo "1. Go to https://railway.app/dashboard"
echo "2. Find your WORKING legacy project"
echo "3. Click Variables tab"
echo "4. Copy the values for:"
echo "   - VITE_SUPABASE_URL"
echo "   - VITE_SUPABASE_ANON_KEY"
echo ""

echo "🎯 Step 2: Set Environment Variables in New Frontend Deployment"
echo "--------------------------------------------------------------"
echo ""
echo "For Vercel (New Frontend):"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Find your NEW frontend project (flyp-frontend)"
echo "3. Click Settings > Environment Variables"
echo "4. Add the SAME values you copied from legacy:"
echo "   - Name: VITE_SUPABASE_URL"
echo "   - Value: [paste from legacy]"
echo "   - Environment: Production, Preview, Development"
echo ""
echo "   - Name: VITE_SUPABASE_ANON_KEY"
echo "   - Value: [paste from legacy]"
echo "   - Environment: Production, Preview, Development"
echo ""

echo "🚀 Step 3: Redeploy New Frontend"
echo "--------------------------------"
echo "1. Go to Deployments tab in your NEW frontend project"
echo "2. Click the three dots on latest deployment"
echo "3. Click 'Redeploy'"
echo "4. Wait for deployment to complete"
echo ""

echo "✅ Step 4: Verify Fix"
echo "---------------------"
echo "1. Visit your NEW frontend production URL"
echo "2. Try to create an account or login"
echo "3. Check browser console - should see no ERR_NAME_NOT_RESOLVED errors"
echo "4. Authentication should work exactly like the legacy app"
echo ""

echo "🔍 Troubleshooting:"
echo "-------------------"
echo "If you still get errors:"
echo "1. Double-check the environment variable values match EXACTLY"
echo "2. Ensure both variables are set in Production environment"
echo "3. Try a fresh deployment after setting variables"
echo "4. Check that your Supabase project is still active"
echo ""

echo "📞 The legacy app works because it has the correct Supabase credentials."
echo "📞 The new frontend just needs the SAME credentials to work identically."
